### ISSUE TITLE
1.14: /ctinsecure reinforcements output both that they are secure and insecure

### ISSUE THREAD

**Issue by Diet-Cola** [CivClassic/Citadel#18]
![image](https://user-images.githubusercontent.com/12645603/72355581-a9a52200-36df-11ea-905e-34d36fc05200.png)

**Comment by Maxopoly** [comment]
This is a general minecraft thing. If you rightclick a block, you interact with it twice. Using left click will only interact once and only show the message once

**Comment by Gjum** [comment]
Could for example ignore right click or debounce it. This issue should remain open until the UI follows intuition.

**Comment by Maxopoly** [comment]
I think ignoring right click has more downsides than upsides. I'll try something to only handle one interact per tick and hope it doesn't have any significant bad side effect

**Comment by Maxopoly** [comment]
Fixed using https://github.com/CivClassic/CivModCore/commit/85f70f692c1cfac778521b626ab26c9f2f4730e0 and https://github.com/CivClassic/Citadel/commit/50290b498c4de961f90163a27bef000e9200de82
