### ISSUE TITLE
1.14: CTR Downgrading appears to be broken

### ISSUE THREAD

**Issue by Diet-Cola** [CivClassic/Citadel#19]
1. Reinforce a block with bedrock (easiest example due to fast mature time)
2. CTR said block with a lower durability material

Outcome will be that the block continues gaining durability past the materials max durability and continue growing in strength until the block is mature. Can be seen here:
![image](https://user-images.githubusercontent.com/12645603/72413621-18c65900-3768-11ea-9edd-4c235add5030.png)

**Comment by Maxopoly** [comment]
Fixed by https://github.com/CivClassic/Citadel/commit/a5c219f92d82334a14fb9016723d51bce49be720
