### ISSUE TITLE
Nerf acid traps

### ISSUE THREAD

**Issue by Maxopoly** [CivClassic/Citadel#23]
Instant aciding makes for rather stupid traps, nowhere is safe and there is no way to detect it. Aciding should have a configurable delay and some kind of indication to nearby players so they can react. Ideally this would also use https://github.com/CivClassic/CivModCore/issues/27

**Comment by Protonull** [comment]
How is this any different to making a piston trap?

**Comment by Maxopoly** [comment]
Piston traps don't allow trapping on reinforced ground. That being said this issue was already mostly addressed by disallowing aciding through solid blocks.

**Comment by Maxopoly** [comment]
Suffciently adressed by making acid not work through solid blocks
