### ISSUE TITLE
ReinforcementLogic#resolveDoubleChestReinforcement

### ISSUE THREAD

**Issue by Maxopoly** [CivClassic/Citadel#26]
https://github.com/CivClassic/Citadel/blob/master/src/main/java/vg/civcraft/mc/citadel/ReinforcementLogic.java#L207

need to properly use

https://hub.spigotmc.org/javadocs/spigot/org/bukkit/block/data/type/Chest.html

to determine where/how the other half is instead of just doing a material check.

**Comment by crimsonblod** [comment]
Potentially related? Doors can be reinforced with two different groups now, one for each block they occupy.

Doublechests can used with hoppers when reinforced if both they and the hopper pulling from them are insecure via the /ctinsecure command.

Insecure hoppers can also push into secure chests.

**Comment by Maxopoly** [comment]
Could you describe the exact procedure to get a door with two different halves?

**Comment by Maxopoly** [comment]
Fixed by https://github.com/CivClassic/Citadel/pull/27
