### ISSUE TITLE
Require /ctb privileges to prevent decay rather than /ctr.

### ISSUE THREAD

**Issue by crimsonblod** [CivClassic/Citadel#29]
In my opinion, the balance of decay would be better if you had to trust somebody with citadel bypass privileges in order for them to prevent decay, mainly because you can trust anybody with /ctr on your groups, but trusting them with the ability to bypass your reinforcements entirely is a much more risky decision. It's certainly not a critical issue, but I just wanted to make sure to log it here so it doesn't get forgotten in the long term,

**Comment by Maxopoly** [comment]
Approved by me, should be a one line change

**Comment by Maxopoly** [comment]
Implemented by https://github.com/CivClassic/Citadel/commit/ac3e848070376124d247c8cbdbb288ae22eae968
