### ISSUE TITLE
Beds need to be reinforced twice

### ISSUE THREAD

**Issue by Maxopoly** [CivClassic/Citadel#35]
I guess resolving from the other part doesn't work

**Comment by Protonull** [comment]
[Here](https://github.com/CivClassic/Citadel/compare/master...Protonull:master#diff-aaa7ed16c43ed2de7eebe1d3f1007295R107-R116) I've updated the bed parser to use block data, rather than the deprecated material data. This *appears* to have fixed it on my test server.

**Comment by Maxopoly** [comment]
Fixed by https://github.com/CivClassic/Citadel/pull/36
