### ISSUE TITLE
Reinforced beacons don't have a beam

### ISSUE THREAD

**Issue by Maxopoly** [CivClassic/Citadel#39]
Most likely this is some kind of block state change we are cancelling.

**Comment by Protonull** [comment]
It's as you suggested in Discord, there's an [if statement](https://github.com/CivClassic/Citadel/blob/master/src/main/java/vg/civcraft/mc/citadel/listener/EntityListener.java#L82) that prevents sand and gravel from ticking reinforcements, that Beacons are being caught and thus being cancelled. That being said, some preliminary investigation, I can't find a Beacon or Beacon-beam entity type.. so I have no idea what entity type would be causing the change. I'll start testing on a live server soon, but it's entirely possible it could be unrelated to sand and gravel checks.

**Comment by Protonull** [comment]
Could you tell me what exactly is happening? I'm having difficulty replicating it on my test server

**Comment by Maxopoly** [comment]
What was reported to me is:

1. Place beacon
2. Reinforce beacon
3. Turn beacon on (chose effect)

Expected: Beacon beam
Instead: No Beam

I think it was Kayla reporting it, ask them.

**Comment by Protonull** [comment]
Tested two different ways:

---

1. * Place an unreinforced beacon (beam appears)
    * Used `/ctr` to reinforce to group (beam remains)
    * Changed the beacon effect. (beam remains)

---

2. * Placed a reinforced beacon (beam appears)
    * Changed the beacon effect. (beam remains)

---

The only plugins I have loaded, excluding ViaVersion, ProtocolLib, and PlugMan, are: CivModCore, Citadel, and NameLayer.

NameLayer and CivModCore were pulled from AnsibleSetup and Citadel was compiled by me with the only change being some console outputs within the `EntityChangeBlockEvent` event, which by the way haven't printed anything during this testing phase.

**Comment by Protonull** [comment]
After starting the Civclassic test server (on 2GB so don't worry), I was able to see the beam while Kayla wasn't. He tested a clean 1.14 and 1.15 client and was able to see the beam, which rules out protocol error. It's likely a mod that's causing the issue, probably Interpol... *again.*
