### ISSUE TITLE
Minecart Hoppers do not dispense items into reinforced hoppers.

### ISSUE THREAD

**Issue by KaloHG** [CivClassic/Citadel#50]
While this may be an intended feature, is there a way that you could find out what the rail the minecart hopper is reinforced to, and then determine if that rail is the same as the hopper below, then have it dispense if it is the same group. 

This would help improve zombie, skeleton, and other various grinder designs greatly.

**Comment by Maxopoly** [comment]
Minecart Hoppers are very laggy and should be used as little as possible. Also the suggested method of using the rail above makes no link to who is actually inputting materials. 
By design entities other than players do not have permission based access to any reinforcements.
