### ISSUE TITLE
Update material names and reinforcement material names to 1.16

### ISSUE THREAD

**Issue by Scuwr** [CivClassic/Citadel#54]
When enabling Citadel, the Legacy Material Support is initialized. The following materials fail to parse:
* "ENDER_PORTAL_FRAME"
* "SAPLING"
* "LONG_GRASS"
* "PISTON_EXTENSION"
* "PISTON_MOVING_PIECE"
* "RED_ROSE"
* "YELLOW_FLOWER"
* "CROPS"
* "SUGAR_CANE_BLOCK"
* "PORTAL"
* "CAKE_BLOCK"
* "NETHER_WARTS"
* "ENDER_PORTAL"

When enabling Citadel, the plugin fails to instantiate the following reinforcements types:
* Reinforcement type at reinforcements.stone had no id
* Reinforcement type at reinforcements.iron had no id
* Reinforcement type at reinforcements.diamond had no id
* Reinforcement type at reinforcements.bedrock had no id

**Comment by Scuwr** [comment]
Fix in https://github.com/CivClassic/Citadel/pull/55

**Comment by Maxopoly** [comment]
Fixed by https://github.com/CivClassic/Citadel/pull/55
