### ISSUE TITLE
Horses don't activate pressure plates

### ISSUE THREAD

**Issue by Lodish** [CivClassic/Citadel#67]
While riding on a horse, pressure plates don't activate so I'm unable to go through the security doors around Westminster that were originally built for horses.

**Comment by Maxopoly** [comment]
Ok. As a temporary fix you can set the doors to insecure if you want.

For fixing this: Need to check any living entities triggering https://hub.spigotmc.org/javadocs/spigot/org/bukkit/event/entity/EntityInteractEvent.html (confirm this is the right one by testing) and do permission checks for passengers. If any match, allow.

**Comment by Protonull** [comment]
Wouldn't be surprised if this is true for all ridable entities such as llamas, pigs, and striders.
