### ISSUE TITLE
Reinforcements aren't dropped on the ground when inventory is full.

### ISSUE THREAD

**Issue by KaloHG** [CivClassic/Citadel#72]
Apparently occurred when an individual broke two diamond reinforced blocks with a full inv, instead of dropping on the ground like the intended behavior, it broke.

[Discord Message Link](https://discord.com/channels/541663751875723267/542076086998007848/796819720799911956) (If you're in CC official)

**Comment by squareblob** [comment]
I have not looked at the Citadel code but it's possible that this is not unique to Citadel and instead Civclassic despawning items more quickly and inconsistently than normal. Earlier today someone complained about some contents of a chest despawning near instantly when the chest was broken, and that was not the only complaint of this sort I have seen lately.

**Comment by Protonull** [comment]
This might sound like a really dumb question, but did they check their armour slots?

**Comment by Maxopoly** [comment]
Can't reproduce, most likely end user incompetence.

**Comment by Protonull** [comment]
> most likely end user incompetence.

10/10 PR move

![Yaaaaaay](https://user-images.githubusercontent.com/52572989/103963482-52e6f280-5151-11eb-8f5a-b1fca82d071d.gif)

**Comment by Maxopoly** [comment]
Ok, it's a non-reoccuring layer 8 error.
